name: Build application

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on:
      - self-hosted
      - linux

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verify Runner
        run: |
          echo "Runner OS: $RUNNER_OS"
          pwd
          whoami

      - name: Build Application
        run: |
          echo "Building the application..."